### ISSUE TITLE
Search results - nothing close to my house

### ISSUE THREAD

**Issue by mldenne** [jh2642/date_night#4]
The search results that came back are interesting. I have a movie theater less than 1 mile from my house, yet it sends me to Avon. The restaurants are interesting, too. Logan's shows up for drinks, yet not as a restaurant...which it should show up for both??

Distances: the distances coming in are interesting, too. My top results are sometime further away or in another city. The good thing is that everything listed is within a 10 mile radius...however, most of the suggestions are at the far edges of that radius.

**Comment by jh2642** [comment]
This could be that your local businesses are not registered with Google Places. Oddly enough, it uses a different API than Google Maps.
